### ISSUE TITLE
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

### ISSUE THREAD

**Issue by aTastyCookie** [Quantika14/email-osint-ripper#3]
Traceback (most recent call last):
  File "eo-ripper.py", line 348, in <module>
    main()
  File "eo-ripper.py", line 319, in main
    attack(email.replace("\n", ""))
  File "eo-ripper.py", line 282, in attack
    br.select_form(nr=0)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 619, in select_form
    global_form = self._factory.global_form
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 260, in global_form
    self.forms()
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 267, in forms
    self._current_forms, self._current_global_form = self._get_forms()
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 282, in _get_forms
    if self.root is None:
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 247, in root
    response, verify=False))
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 149, in content_parser
    namespaceHTMLElements=False)
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

**Comment by Quantika14** [comment]
Lo arreglamos. Usamos un servicio externo web para verificar si el correo existe.
Eso era lo que fallaba. Ya está arreglado.
Gracias.
```
try:
		html = br.open(url)
		br.select_form(nr=0)
		br.form['email'] = email
		br.submit()
```

**Comment by Pfesi** [comment]
I'm still having issues even after I updated html5lib. Is there any other way to solve the 
" TypeError: parse() got an unexpected keyword argument 'transport_encoding'     "
error?

**Comment by colinwxl** [comment]
I got the same error when I executed 'br.select_form(nr=0)'

**Comment by lightbandit** [comment]
When I try to use pip install like you said, this is what I get:

`Installing collected packages: six, setuptools, html5lib
  Found existing installation: six 1.4.1
DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
OSError: [Errno 1] Operation not permitted: '/tmp/pip-KjP1w5-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'`

**Comment by momen84** [comment]
colinwxl solution worked for me

**Comment by SachinNarkhede** [comment]
(C:\Python35) C:\Users\Administrator\rasa_core>pip install -r requirements.txt
Obtaining file:///C:/Users/Administrator/rasa_core (from -r requirements.txt (li
ne 2))
Collecting apscheduler==3.3.1 (from -r requirements.txt (line 3))
Exception:
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python35\lib\site-packages\pip\commands\install.py", line 335, in run

    wb.build(autobuilding=True)
  File "C:\Python35\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Python35\lib\site-packages\pip\req\req_set.py", line 380, in prepare_
files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Python35\lib\site-packages\pip\req\req_set.py", line 554, in _prepare
_file
    require_hashes
  File "C:\Python35\lib\site-packages\pip\req\req_install.py", line 278, in popu
late_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Python35\lib\site-packages\pip\index.py", line 465, in find_requireme
nt
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Python35\lib\site-packages\pip\index.py", line 423, in find_all_candi
dates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Python35\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Python35\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Python35\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Python35\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'
